"""
Some web resources for downloading UAVSAR data

Requires python module Mechanize (http://wwwsearch.sourceforge.net/mechanize/)

Copyright (C) 2013   Brent M. Minchew
--------------------------------------------------------------------
GNU Licensed

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

--------------------------------------------------------------------
"""
import sys,os

VERSION = '0.1.0'

def write_version_py(filename='version.py'):
   cnt = '"""' + __doc__
   cnt += ' ** This file was generated by the root setup.py\n' + '"""'
   cnt += """ 

version = '%(version)s'
"""
   a = open(filename, 'w')
   try:
      a.write(cnt % {'version': VERSION})
   finally:
      a.close()

def configuration(parent_package='',top_path=None):
   from numpy.distutils.misc_util import Configuration
   config = Configuration(None, parent_package, top_path)
   config.set_options(ignore_setup_xxx_py=True,
                       assume_default_configuration=True,
                       delegate_options_to_subpackages=True,
                       quiet=True)
   config.add_scripts('uavsar_insar_download.py',
                        'uavsar_polsar_download.py',
                        'http_retrieve.py')
   config.get_version('version.py')
   return config

def setup_package():
   from distutils.dir_util import remove_tree
   from numpy.distutils.core import setup   
   write_version_py()
   if os.path.exists('./build'):  
      remove_tree('./build')
   setup(name='uavsar_webpy',
      author='Brent Minchew',
      author_email='bminchew@caltech.edu',
      description='\n'.join(__doc__.split('\n')[:1]),
      license = 'GNU',
      classifiers=[
      'Development Status :: 4 - Beta',
      'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
      'Programming Language :: Python',
      'Operating System :: OS Independent',
      'Intended Audience :: Science/Research',
      'Topic :: Scientific/Engineering'],
      configuration=configuration)

if __name__ == '__main__':
   setup_package()

